name: Lints

on: [push]

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: npm install
      - name: Update Modules
        run: npm run update
      - name: Run linter
        run: npm run lint
